// Questions Disney - Niveau Taram (Extrême) - 200 questions
const taramquestions = [
    {"id": "t1", "question": "Quel est le nom du cochon dans 'Taram et le Chaudron Magique' ?", "options": ["Tirelire", "Cochinet", "Hen Wen", "Porcinet"], "correct": 2},
    {"id": "t2", "question": "Combien de minutes de 'Taram' ont été coupées avant la sortie ?", "options": ["5 minutes", "12 minutes", "25 minutes", "30 minutes"], "correct": 1},
    {"id": "t3", "question": "Quel est le numéro de production interne de 'Dumbo' ?", "options": ["#3", "#4", "#5", "#6"], "correct": 1},
    {"id": "t4", "question": "Dans 'The Rescuers Down Under', quel est le nom de l'aigle ?", "options": ["Orville", "Wilbur", "Marahute", "Cody"], "correct": 2},
    {"id": "t5", "question": "Quel film Disney a été supprimé des archives entre 1946 et 2009 ?", "options": ["Mélodie du Sud", "Fantasia", "Les Trois Caballeros", "Saludos Amigos"], "correct": 0},
    {"id": "t6", "question": "Combien de cellulos ont été utilisés pour 'Blanche-Neige' ?", "options": ["50 000", "100 000", "250 000", "Plus de 200 000"], "correct": 3},
    {"id": "t7", "question": "Quel est le nom du système d'animation Disney de 1990 ?", "options": ["CAPS", "PIXAR", "ANIMO", "TOONZ"], "correct": 0},
    {"id": "t8", "question": "Dans 'Basil, Détective Privé', à quelle adresse vit Basil ?", "options": ["221B Baker Street", "221 1/2 Baker Street", "220B Baker Street", "Baker Street Underground"], "correct": 1},
    {"id": "t9", "question": "Combien d'animateurs ont travaillé sur 'Le Roi Lion' ?", "options": ["50", "100", "600", "Plus de 800"], "correct": 2},
    {"id": "t10", "question": "Quel film Disney utilise la caméra multiplane à 7 niveaux ?", "options": ["Blanche-Neige", "Pinocchio", "Fantasia", "Bambi"], "correct": 1},
    {"id": "t11", "question": "Qui prête sa voix au Seigneur des Ténèbres dans 'Taram' (VO) ?", "options": ["John Hurt", "Tim Curry", "Christopher Lee", "James Earl Jones"], "correct": 0},
    {"id": "t12", "question": "Combien de dessins originaux pour 'Fantasia' ?", "options": ["500 000", "750 000", "1 million", "Plus de 1 million"], "correct": 3},
    {"id": "t13", "question": "Quel est le vrai nom de l'antagoniste dans 'Taram' ?", "options": ["Le Seigneur Noir", "Le Roi Cornu", "Arawn", "Prydain"], "correct": 1},
    {"id": "t14", "question": "Dans 'Oliver & Compagnie', quel véhicule conduit Fagin ?", "options": ["Ford", "Chevrolet", "Scooter trois roues", "Vespa"], "correct": 2},
    {"id": "t15", "question": "Quel premier film Disney a une chanson nominée aux Grammy ?", "options": ["Mary Poppins", "Le Livre de la Jungle", "La Petite Sirène", "Blanche-Neige"], "correct": 3},
    {"id": "t16", "question": "Combien de temps a duré la production de 'Sleeping Beauty' ?", "options": ["4 ans", "6 ans", "8 ans", "10 ans"], "correct": 3},
    {"id": "t17", "question": "Quel film Disney détient le record du plus long développement ?", "options": ["Fantasia 2000", "Dinosaure", "La Reine des Neiges", "Raiponce"], "correct": 3},
    {"id": "t18", "question": "Dans 'Hercule', combien de Titans sont libérés par Hadès ?", "options": ["3", "4", "5", "6"], "correct": 1},
    {"id": "t19", "question": "Quel animateur est surnommé 'le père de Mickey Mouse' ?", "options": ["Ub Iwerks", "Les Clark", "Ward Kimball", "Eric Larson"], "correct": 0},
    {"id": "t20", "question": "Quel premier film d'animation a été présenté en compétition à Cannes ?", "options": ["Shrek", "Persepolis", "WALL-E", "Valse avec Bashir"], "correct": 0},
    {"id": "t21", "question": "Dans 'Atlantide', combien de langues Milo parle-t-il ?", "options": ["5", "10", "Plus de 15", "Plus de 25"], "correct": 2},
    {"id": "t22", "question": "Quel studio a été racheté par Disney en 2006 ?", "options": ["DreamWorks", "Pixar", "Blue Sky", "Illumination"], "correct": 1},
    {"id": "t23", "question": "Combien coûtait un ticket Disneyland le jour d'ouverture (1955) ?", "options": ["0,50 $", "1 $", "5 $", "10 $"], "correct": 1},
    {"id": "t24", "question": "Quel est le nom de code du projet 'Dinosaure' (2000) ?", "options": ["Project Extinction", "Project Prehistoric", "Project Genesis", "Dawn of Time"], "correct": 2},
    {"id": "t25", "question": "Quel compositeur a refusé de travailler sur 'La Petite Sirène' ?", "options": ["Hans Zimmer", "Howard Ashman", "Tim Rice", "Elton John"], "correct": 0},
    {"id": "t26", "question": "Quel était le titre de travail de 'Toy Story' ?", "options": ["Toy World", "The Toy Story", "Toys", "Made in Taiwan"], "correct": 2},
    {"id": "t27", "question": "Quelle version de Woody a été rejetée pendant la production ?", "options": ["Woody le gentil", "Woody le sarcastique", "Woody le méchant", "Woody le triste"], "correct": 2},
    {"id": "t28", "question": "Combien de polygones composaient Woody dans Toy Story 1 ?", "options": ["200 000", "500 000", "700 000", "1 million"], "correct": 2},
    {"id": "t29", "question": "Quel personnage Pixar apparaît en easter egg dans presque tous les films ?", "options": ["Woody", "Luxo Jr.", "Nemo", "Mike Wazowski"], "correct": 1},
    {"id": "t30", "question": "Quelle était la résolution de rendu de Toy Story 1 ?", "options": ["720p", "1080p", "1536 x 922", "2K"], "correct": 2},
    {"id": "t31", "question": "Combien de temps de rendu par frame pour Toy Story ?", "options": ["1-2 heures", "4-13 heures", "24 heures", "48 heures"], "correct": 1},
    {"id": "t32", "question": "Quelle société a failli acheter Pixar avant Disney ?", "options": ["Microsoft", "Apple", "Sony", "Warner Bros"], "correct": 0},
    {"id": "t33", "question": "Qui était le PDG de Pixar lors du rachat par Disney ?", "options": ["John Lasseter", "Ed Catmull", "Steve Jobs", "Bob Iger"], "correct": 2},
    {"id": "t34", "question": "Combien d'actions Disney Steve Jobs a-t-il reçues pour Pixar ?", "options": ["3%", "5%", "7%", "10%"], "correct": 2},
    {"id": "t35", "question": "Quelle technologie Pixar a-t-elle inventée pour le rendu ?", "options": ["RenderMan", "Maya", "3D Max", "Blender"], "correct": 0},
    {"id": "t36", "question": "Combien d'Oscars techniques RenderMan a-t-il reçus ?", "options": ["1", "2", "3", "4"], "correct": 2},
    {"id": "t37", "question": "Quel était le premier court-métrage Pixar ?", "options": ["Luxo Jr.", "Red's Dream", "The Adventures of André & Wally B.", "Tin Toy"], "correct": 2},
    {"id": "t38", "question": "En quelle année Pixar a-t-il été fondé ?", "options": ["1979", "1984", "1986", "1989"], "correct": 2},
    {"id": "t39", "question": "De quelle entreprise Pixar est-il issu à l'origine ?", "options": ["Apple", "Lucasfilm", "Industrial Light & Magic", "George Lucas Computers"], "correct": 1},
    {"id": "t40", "question": "Combien George Lucas a-t-il vendu Pixar ?", "options": ["5 millions $", "10 millions $", "15 millions $", "20 millions $"], "correct": 1},
    {"id": "t41", "question": "Quel était le vrai business de Pixar avant les films ?", "options": ["Jeux vidéo", "Ordinateurs graphiques", "Publicité", "Effets spéciaux"], "correct": 1},
    {"id": "t42", "question": "Comment s'appelait l'ordinateur que vendait Pixar ?", "options": ["Pixar Image Computer", "RenderBox", "GraphicsStation", "AnimationPC"], "correct": 0},
    {"id": "t43", "question": "Combien coûtait le Pixar Image Computer ?", "options": ["30 000 $", "60 000 $", "135 000 $", "200 000 $"], "correct": 2},
    {"id": "t44", "question": "Quelle société a été le plus gros client du Pixar Image Computer ?", "options": ["NASA", "Disney", "Gouvernement US", "Hôpitaux"], "correct": 2},
    {"id": "t45", "question": "Quel film Pixar a utilisé le plus de puissance de calcul ?", "options": ["Toy Story 4", "Coco", "Soul", "Les Indestructibles 2"], "correct": 0},
    {"id": "t46", "question": "Combien de cheveux Sully a-t-il dans Monstres & Cie ?", "options": ["1 million", "2,3 millions", "5 millions", "10 millions"], "correct": 1},
    {"id": "t47", "question": "Quelle nouvelle technologie a été créée pour les cheveux de Sully ?", "options": ["HairSim", "FurTech", "Fizt", "HairMaster"], "correct": 2},
    {"id": "t48", "question": "Combien de portes différentes apparaissent dans Monstres & Cie ?", "options": ["500", "1 000", "2 500", "5 000"], "correct": 2},
    {"id": "t49", "question": "Quel film Pixar a le plus de personnages ?", "options": ["Finding Nemo", "Coco", "Toy Story 4", "Ratatouille"], "correct": 1},
    {"id": "t50", "question": "Combien de squelettes uniques dans Coco ?", "options": ["50", "100", "Plus de 200", "Plus de 500"], "correct": 2},
    {"id": "t51", "question": "Quelle est la plus longue scène de foule jamais animée par Pixar ?", "options": ["Coco - La Terre des Morts", "Toy Story 4 - le carnaval", "Finding Nemo - le récif", "Les Indestructibles - la bataille finale"], "correct": 0},
    {"id": "t52", "question": "Combien de temps a duré le développement de Raiponce ?", "options": ["4 ans", "6 ans", "10 ans", "14 ans"], "correct": 2},
    {"id": "t53", "question": "Quel était le titre original de Raiponce ?", "options": ["Rapunzel", "The Tower", "Rapunzel Unbraided", "Hair"], "correct": 2},
    {"id": "t54", "question": "Quel est le budget de Raiponce ?", "options": ["160 millions $", "200 millions $", "260 millions $", "300 millions $"], "correct": 2},
    {"id": "t55", "question": "Pourquoi le titre a-t-il changé en 'Tangled' ?", "options": ["Plus moderne", "Attirer les garçons", "Problèmes de droits", "Focus marketing"], "correct": 1},
    {"id": "t56", "question": "Combien de cheveux a Raiponce dans le film ?", "options": ["27 000", "50 000", "100 000", "140 000"], "correct": 3},
    {"id": "t57", "question": "Quelle est la longueur des cheveux de Raiponce ?", "options": ["15 mètres", "21 mètres", "30 mètres", "50 mètres"], "correct": 1},
    {"id": "t58", "question": "Quelle nouvelle technologie a été créée pour les cheveux de Raiponce ?", "options": ["HairSim", "Dynamic Wires", "MegaHair", "FlowHair"], "correct": 1},
    {"id": "t59", "question": "Quel film Disney Animation a rapporté le plus au box-office ?", "options": ["La Reine des Neiges 2", "Le Roi Lion 2019", "Zootopie", "Vaiana"], "correct": 0},
    {"id": "t60", "question": "Combien La Reine des Neiges 2 a-t-elle rapporté ?", "options": ["1 milliard $", "1,2 milliards $", "1,45 milliards $", "1,6 milliards $"], "correct": 2},
    {"id": "t61", "question": "Quel film a le record du meilleur démarrage pour un film d'animation ?", "options": ["Toy Story 4", "Les Indestructibles 2", "La Reine des Neiges 2", "Le Roi Lion 2019"], "correct": 2},
    {"id": "t62", "question": "Combien 'Let It Go' a-t-elle généré en ventes ?", "options": ["5 millions", "10 millions", "Plus de 10 millions", "Plus de 20 millions"], "correct": 2},
    {"id": "t63", "question": "Combien de versions de 'Let It Go' ont été enregistrées pour le monde ?", "options": ["25", "41", "55", "70"], "correct": 1},
    {"id": "t64", "question": "Quelle chanteuse a enregistré la version pop de 'Let It Go' ?", "options": ["Idina Menzel", "Demi Lovato", "Ariana Grande", "Taylor Swift"], "correct": 1},
    {"id": "t65", "question": "Combien de vues YouTube 'Let It Go' a-t-elle accumulées ?", "options": ["500 millions", "1 milliard", "Plus de 2 milliards", "Plus de 3 milliards"], "correct": 2},
    {"id": "t66", "question": "Quelle était la chanson originale prévue pour le climax de Frozen ?", "options": ["Let It Go", "Life's Too Short", "For the First Time in Forever", "Do You Want to Build a Snowman"], "correct": 1},
    {"id": "t67", "question": "Pourquoi 'Life's Too Short' a-t-elle été coupée ?", "options": ["Trop longue", "Elsa trop méchante", "Pas assez catchy", "Problèmes de voix"], "correct": 1},
    {"id": "t68", "question": "Quel personnage devait être le méchant original de Frozen ?", "options": ["Hans", "Elsa", "Le duc de Weselton", "Kristoff"], "correct": 1},
    {"id": "t69", "question": "Quand le rôle d'Elsa a-t-il changé de méchante à héroïne ?", "options": ["Après 'Let It Go'", "Dès le début", "Après le premier test", "Jamais changé"], "correct": 0},
    {"id": "t70", "question": "Combien de flocons de neige uniques ont été créés pour Frozen ?", "options": ["500", "1 000", "2 000", "Plus de 2 000"], "correct": 3},
    {"id": "t71", "question": "Quelle technologie a été développée pour la neige de Frozen ?", "options": ["SnowSim", "Matterhorn", "FrozenFX", "IceGen"], "correct": 1},
    {"id": "t72", "question": "Combien d'éléments de glace ont été créés pour le palais d'Elsa ?", "options": ["5 000", "15 000", "50 000", "Plus de 50 000"], "correct": 3},
    {"id": "t73", "question": "Quelle actrice double Elsa en VO ?", "options": ["Kristen Bell", "Idina Menzel", "Demi Moore", "Amy Adams"], "correct": 1},
    {"id": "t74", "question": "Dans quelle comédie musicale Idina Menzel est-elle devenue célèbre ?", "options": ["Les Misérables", "Wicked", "Rent", "Chicago"], "correct": 1},
    {"id": "t75", "question": "Quel rôle jouait Idina Menzel dans Wicked ?", "options": ["Glinda", "Elphaba", "Nessarose", "Madame Morrible"], "correct": 1},
    {"id": "t76", "question": "Qui double Anna en VO ?", "options": ["Idina Menzel", "Kristen Bell", "Mandy Moore", "Demi Lovato"], "correct": 1},
    {"id": "t77", "question": "Dans quelle série TV Kristen Bell a-t-elle joué avant Frozen ?", "options": ["Gossip Girl", "Veronica Mars", "Heroes", "Smallville"], "correct": 1},
    {"id": "t78", "question": "Qui est le compositeur de Frozen (musique de film, pas chansons) ?", "options": ["Alan Menken", "Christophe Beck", "Hans Zimmer", "Danny Elfman"], "correct": 1},
    {"id": "t79", "question": "Qui a composé les chansons de Frozen ?", "options": ["Alan Menken", "Robert Lopez et Kristen Anderson-Lopez", "Lin-Manuel Miranda", "Stephen Schwartz"], "correct": 1},
    {"id": "t80", "question": "Pour quelle série les Lopez ont-ils gagné un Emmy avant Frozen ?", "options": ["Les Simpson", "South Park", "Family Guy", "Bob's Burgers"], "correct": 0},
    {"id": "t81", "question": "Quel award EGOT Robert Lopez a-t-il complété avec Frozen ?", "options": ["Emmy", "Grammy", "Oscar", "Tony"], "correct": 2},
    {"id": "t82", "question": "Combien de personnes ont atteint le statut EGOT ?", "options": ["5", "10", "17", "25"], "correct": 2},
    {"id": "t83", "question": "Quel film des Lopez a précédé Frozen ?", "options": ["Avenue Q", "The Book of Mormon", "Coco", "Winnie the Pooh 2011"], "correct": 3},
    {"id": "t84", "question": "Combien coûte une robe Elsa officielle Disney ?", "options": ["50-80 $", "100-150 $", "200-300 $", "Variable selon les versions"], "correct": 3},
    {"id": "t85", "question": "Combien de dollars de merchandise Frozen a-t-il généré la première année ?", "options": ["500 millions $", "1 milliard $", "3 milliards $", "Plus de 5 milliards $"], "correct": 2},
    {"id": "t86", "question": "Quel film détient le record de merchandise Disney ?", "options": ["Star Wars", "Frozen", "Cars", "Mickey Mouse"], "correct": 2},
    {"id": "t87", "question": "Combien Cars a-t-il généré en merchandise total ?", "options": ["5 milliards $", "10 milliards $", "Plus de 10 milliards $", "Plus de 30 milliards $"], "correct": 2},
    {"id": "t88", "question": "Pourquoi Cars génère autant de merchandise ?", "options": ["Les enfants aiment les voitures", "Renouvellement des jouets", "Marketing agressif", "Toutes ces raisons"], "correct": 3},
    {"id": "t89", "question": "Quel était le premier Pixar à ne pas être numéro 1 au box-office ?", "options": ["Cars 2", "Monsters University", "Le Voyage d'Arlo", "Onward"], "correct": 2},
    {"id": "t90", "question": "Quel film Pixar a été le moins rentable ?", "options": ["Le Voyage d'Arlo", "Onward", "Luca", "Elemental"], "correct": 0},
    {"id": "t91", "question": "Quel film Pixar a eu le développement le plus difficile ?", "options": ["Toy Story 2", "Ratatouille", "Le Voyage d'Arlo", "Cars 3"], "correct": 2},
    {"id": "t92", "question": "Combien de réalisateurs Le Voyage d'Arlo a-t-il eu ?", "options": ["1", "2", "3", "4"], "correct": 2},
    {"id": "t93", "question": "Quel réalisateur original a quitté Le Voyage d'Arlo ?", "options": ["Pete Docter", "Bob Peterson", "Dan Scanlon", "Lee Unkrich"], "correct": 1},
    {"id": "t94", "question": "Quel film Pixar a été entièrement recommencé à mi-production ?", "options": ["Toy Story 2", "Ratatouille", "Le Voyage d'Arlo", "Les deux premiers"], "correct": 3},
    {"id": "t95", "question": "Qui a remplacé Jan Pinkava sur Ratatouille ?", "options": ["Andrew Stanton", "Brad Bird", "Lee Unkrich", "Pete Docter"], "correct": 1},
    {"id": "t96", "question": "Pourquoi Jan Pinkava a-t-il quitté Ratatouille ?", "options": ["Différences créatives", "Problèmes personnels", "Autre projet", "Maladie"], "correct": 0},
    {"id": "t97", "question": "Quel autre film Brad Bird a-t-il réalisé pour Pixar ?", "options": ["Cars", "Les Indestructibles", "Up", "Coco"], "correct": 1},
    {"id": "t98", "question": "Quel film non-Pixar Brad Bird a-t-il réalisé ?", "options": ["Le Géant de Fer", "Shrek", "Madagascar", "L'Âge de Glace"], "correct": 0},
    {"id": "t99", "question": "Quel film live-action Brad Bird a-t-il réalisé ?", "options": ["Star Trek", "Mission Impossible 4", "James Bond", "Transformers"], "correct": 1},
    {"id": "t100", "question": "Quel réalisateur Pixar a le plus d'Oscars ?", "options": ["John Lasseter", "Pete Docter", "Andrew Stanton", "Lee Unkrich"], "correct": 1},
    {"id": "t101", "question": "Combien d'Oscars Pete Docter a-t-il remportés ?", "options": ["1", "2", "3", "4"], "correct": 2},
    {"id": "t102", "question": "Pour quels films Pete Docter a-t-il gagné l'Oscar ?", "options": ["Up et Vice-Versa", "Vice-Versa et Soul", "Up et Soul", "Monstres & Cie et Up"], "correct": 2},
    {"id": "t103", "question": "Quel poste Pete Docter occupe-t-il actuellement chez Pixar ?", "options": ["Réalisateur", "Directeur créatif", "PDG", "Président"], "correct": 1},
    {"id": "t104", "question": "Qui a remplacé John Lasseter après son départ ?", "options": ["Pete Docter", "Jennifer Lee", "Les deux", "Ed Catmull"], "correct": 2},
    {"id": "t105", "question": "Pourquoi John Lasseter a-t-il quitté Disney/Pixar ?", "options": ["Retraite", "Accusations de harcèlement", "Nouveau projet", "Problèmes de santé"], "correct": 1},
    {"id": "t106", "question": "Où John Lasseter travaille-t-il maintenant ?", "options": ["DreamWorks", "Skydance Animation", "Illumination", "Sony"], "correct": 1},
    {"id": "t107", "question": "Quel premier film Skydance Animation avec Lasseter est sorti ?", "options": ["Luck", "Spellbound", "The Tiger's Apprentice", "Aucun encore"], "correct": 0},
    {"id": "t108", "question": "Quelle plateforme a diffusé 'Luck' de Skydance ?", "options": ["Netflix", "Disney+", "Apple TV+", "Amazon Prime"], "correct": 2},
    {"id": "t109", "question": "Combien de films Disney Animation Jennifer Lee a-t-elle écrits ?", "options": ["2", "3", "4", "5"], "correct": 1},
    {"id": "t110", "question": "Quel poste Jennifer Lee occupe-t-elle chez Disney Animation ?", "options": ["Réalisatrice", "Directrice créative", "Scénariste en chef", "Présidente"], "correct": 1},
    {"id": "t111", "question": "Quel film Jennifer Lee a-t-elle co-réalisé ?", "options": ["La Reine des Neiges", "Vaiana", "Encanto", "Zootopie"], "correct": 0},
    {"id": "t112", "question": "Quelle femme a été la première réalisatrice d'un film Disney Animation ?", "options": ["Jennifer Lee", "Brenda Chapman", "Jill Culton", "Vicky Jenson"], "correct": 0},
    {"id": "t113", "question": "Quelle réalisatrice a co-créé Rebelle avant de partir ?", "options": ["Jennifer Lee", "Brenda Chapman", "Jill Culton", "Nicole Paradis Grindle"], "correct": 1},
    {"id": "t114", "question": "Pourquoi Brenda Chapman a-t-elle quitté Rebelle ?", "options": ["Différences créatives", "Problèmes personnels", "Autre projet", "Elle n'a pas quitté"], "correct": 0},
    {"id": "t115", "question": "Quel réalisateur a terminé Rebelle ?", "options": ["Pete Docter", "Mark Andrews", "Dan Scanlon", "Lee Unkrich"], "correct": 1},
    {"id": "t116", "question": "Rebelle a-t-il remporté l'Oscar du meilleur film d'animation ?", "options": ["Oui", "Non", "Nominé seulement", "N'était pas éligible"], "correct": 0},
    {"id": "t117", "question": "Quel était le premier film Pixar situé en dehors des USA ?", "options": ["Ratatouille", "Cars 2", "Rebelle", "Coco"], "correct": 0},
    {"id": "t118", "question": "Dans combien de pays se déroule Cars 2 ?", "options": ["3", "5", "7", "Plus de 5"], "correct": 3},
    {"id": "t119", "question": "Quel pays n'apparaît PAS dans Cars 2 ?", "options": ["Japon", "Italie", "France", "Allemagne"], "correct": 3},
    {"id": "t120", "question": "Combien Cars 2 a-t-il rapporté au box-office ?", "options": ["300 millions $", "462 millions $", "560 millions $", "650 millions $"], "correct": 1},
    {"id": "t121", "question": "Quelle note Cars 2 a-t-il sur Rotten Tomatoes ?", "options": ["29%", "39%", "49%", "59%"], "correct": 1},
    {"id": "t122", "question": "Quel film Pixar a la plus basse note critique ?", "options": ["Cars 2", "Le Voyage d'Arlo", "Cars 3", "Monsters University"], "correct": 0},
    {"id": "t123", "question": "Quel film Pixar a la plus haute note sur Rotten Tomatoes ?", "options": ["Toy Story", "Toy Story 2", "Finding Nemo", "Coco"], "correct": 1},
    {"id": "t124", "question": "Quelle note Toy Story 2 a-t-il sur Rotten Tomatoes ?", "options": ["95%", "98%", "100%", "99%"], "correct": 2},
    {"id": "t125", "question": "Combien de films ont 100% sur Rotten Tomatoes ?", "options": ["Toy Story 2 seul", "Toy Story 1 et 2", "Aucun Pixar", "Plusieurs"], "correct": 0},
    {"id": "t126", "question": "Quel film Disney Animation a 100% sur Rotten Tomatoes ?", "options": ["Pinocchio", "Dumbo", "Zootopie", "Aucun"], "correct": 0},
    {"id": "t127", "question": "Quel est le score Rotten Tomatoes de La Belle et la Bête (1991) ?", "options": ["90%", "93%", "95%", "94%"], "correct": 1},
    {"id": "t128", "question": "Quel film Disney classique a le plus bas score RT ?", "options": ["Dumbo", "Pinocchio", "Frère des Ours", "Chicken Little"], "correct": 3},
    {"id": "t129", "question": "Quelle note Chicken Little a-t-il sur RT ?", "options": ["26%", "36%", "46%", "56%"], "correct": 2},
    {"id": "t130", "question": "Pourquoi Chicken Little est-il considéré comme un échec ?", "options": ["Box-office", "Critiques", "Il a été un succès", "Les deux A et B"], "correct": 1},
    {"id": "t131", "question": "Combien Chicken Little a-t-il rapporté au box-office ?", "options": ["100 millions $", "200 millions $", "314 millions $", "400 millions $"], "correct": 2},
    {"id": "t132", "question": "Quel était le premier film CGI de Disney Animation (pas Pixar) ?", "options": ["Dinosaure", "Chicken Little", "Bienvenue chez les Robinson", "Volt"], "correct": 1},
    {"id": "t133", "question": "Quel film a marqué le début du 'Revival' Disney ?", "options": ["Volt", "La Princesse et la Grenouille", "Raiponce", "Winnie l'Ourson 2011"], "correct": 1},
    {"id": "t134", "question": "Quel film a confirmé le succès du Revival ?", "options": ["La Princesse et la Grenouille", "Raiponce", "Winnie l'Ourson", "Les Mondes de Ralph"], "correct": 1},
    {"id": "t135", "question": "Combien de films composent le Disney Revival ?", "options": ["8", "10", "12", "14"], "correct": 2},
    {"id": "t136", "question": "Quel film du Revival a le plus gros box-office ?", "options": ["La Reine des Neiges", "La Reine des Neiges 2", "Zootopie", "Vaiana"], "correct": 1},
    {"id": "t137", "question": "Quel film du Revival a remporté l'Oscar du meilleur film d'animation le premier ?", "options": ["La Reine des Neiges", "Les Nouveaux Héros", "Zootopie", "Coco"], "correct": 0},
    {"id": "t138", "question": "Combien d'Oscars du meilleur film d'animation le Revival a-t-il remportés ?", "options": ["2", "3", "4", "5"], "correct": 2},
    {"id": "t139", "question": "Quel film du Revival n'a PAS été nominé à l'Oscar ?", "options": ["Raiponce", "Les Mondes de Ralph", "Vaiana", "Raya et le Dernier Dragon"], "correct": 0},
    {"id": "t140", "question": "Pourquoi Raiponce n'a pas été nominé aux Oscars ?", "options": ["Pas assez bon", "Catégorie trop compétitive", "Erreur de soumission", "Problèmes de distribution"], "correct": 1},
    {"id": "t141", "question": "Quel film a battu Raiponce aux Oscars 2011 ?", "options": ["Toy Story 3", "How to Train Your Dragon", "Despicable Me", "The Illusionist"], "correct": 0},
    {"id": "t142", "question": "Combien de nominations Toy Story 3 a-t-il reçues ?", "options": ["3", "5", "7", "9"], "correct": 1},
    {"id": "t143", "question": "Toy Story 3 a-t-il été nominé pour le meilleur film ?", "options": ["Oui", "Non", "Seulement meilleur scénario", "Seulement animation"], "correct": 0},
    {"id": "t144", "question": "Quel autre film d'animation a été nominé pour le meilleur film ?", "options": ["La Belle et la Bête, Up, Toy Story 3", "Shrek, Finding Nemo, WALL-E", "Spirited Away, Coco, Soul", "The Lion King, Frozen, Zootopia"], "correct": 0},
    {"id": "t145", "question": "Quel film d'animation a failli gagner le meilleur film aux Oscars ?", "options": ["La Belle et la Bête", "Up", "Toy Story 3", "Aucun n'était proche"], "correct": 0},
    {"id": "t146", "question": "En quelle année la catégorie meilleur film d'animation a-t-elle été créée ?", "options": ["1998", "2001", "2003", "2005"], "correct": 1},
    {"id": "t147", "question": "Quel film a remporté le premier Oscar du meilleur film d'animation ?", "options": ["Shrek", "Monsters Inc.", "Ice Age", "Lilo & Stitch"], "correct": 0},
    {"id": "t148", "question": "Combien d'Oscars du meilleur film d'animation Pixar a-t-il remportés ?", "options": ["8", "10", "11", "12"], "correct": 2},
    {"id": "t149", "question": "Combien d'Oscars du meilleur film d'animation Disney Animation a-t-il ?", "options": ["3", "4", "5", "6"], "correct": 1},
    {"id": "t150", "question": "Quel studio non-Disney/Pixar a le plus d'Oscars d'animation ?", "options": ["DreamWorks", "Studio Ghibli", "Aardman", "Laika"], "correct": 1},
    {"id": "t151", "question": "Combien d'Oscars Studio Ghibli a-t-il remportés ?", "options": ["1", "2", "3", "4"], "correct": 0},
    {"id": "t152", "question": "Quel film Ghibli a remporté l'Oscar ?", "options": ["Mon Voisin Totoro", "Princesse Mononoké", "Le Voyage de Chihiro", "Le Château Ambulant"], "correct": 2},
    {"id": "t153", "question": "Quelle relation Disney avait-il avec Studio Ghibli ?", "options": ["Propriétaire", "Distributeur US", "Co-producteur", "Aucune"], "correct": 1},
    {"id": "t154", "question": "Jusqu'à quand Disney a-t-il distribué Ghibli aux USA ?", "options": ["2010", "2017", "2020", "Toujours en cours"], "correct": 1},
    {"id": "t155", "question": "Qui distribue maintenant Ghibli aux USA ?", "options": ["Universal", "Warner Bros", "GKIDS", "Sony"], "correct": 2},
    {"id": "t156", "question": "Quel service de streaming a les films Ghibli ?", "options": ["Disney+", "Netflix", "HBO Max", "Amazon Prime"], "correct": 2},
    {"id": "t157", "question": "Dans combien de pays HBO Max est-il disponible ?", "options": ["USA seulement", "Amérique du Nord", "60+ pays", "Monde entier"], "correct": 2},
    {"id": "t158", "question": "Quel studio Hayao Miyazaki a-t-il fondé ?", "options": ["Toei Animation", "Studio Ghibli", "Madhouse", "Sunrise"], "correct": 1},
    {"id": "t159", "question": "Qui a cofondé Studio Ghibli avec Miyazaki ?", "options": ["Mamoru Hosoda", "Isao Takahata", "Satoshi Kon", "Makoto Shinkai"], "correct": 1},
    {"id": "t160", "question": "Quel était le premier film de Studio Ghibli ?", "options": ["Nausicaä", "Le Château dans le Ciel", "Mon Voisin Totoro", "Kiki la petite sorcière"], "correct": 1},
    {"id": "t161", "question": "Pourquoi Nausicaä n'est pas techniquement un film Ghibli ?", "options": ["Trop court", "Fait avant la fondation du studio", "Co-production", "Problèmes de droits"], "correct": 1},
    {"id": "t162", "question": "Quel réalisateur Disney a été influencé par Miyazaki ?", "options": ["John Lasseter", "Pete Docter", "Brad Bird", "Tous ces réalisateurs"], "correct": 3},
    {"id": "t163", "question": "Qui a présenté Miyazaki à John Lasseter ?", "options": ["Steve Jobs", "Toshio Suzuki", "Personne, ils se sont rencontrés seuls", "Joe Hisaishi"], "correct": 1},
    {"id": "t164", "question": "Quelle influence Totoro a-t-il eu sur Toy Story ?", "options": ["Le design de personnages", "L'histoire", "Un easter egg", "Aucune"], "correct": 2},
    {"id": "t165", "question": "Dans quel film Pixar voit-on une peluche Totoro ?", "options": ["Toy Story", "Toy Story 3", "Monsters Inc.", "Up"], "correct": 1},
    {"id": "t166", "question": "Quel autre film contient un easter egg Ghibli ?", "options": ["Finding Nemo", "The Incredibles", "Ratatouille", "Aucun autre"], "correct": 0},
    {"id": "t167", "question": "Quel compositeur a travaillé sur tous les films de Miyazaki ?", "options": ["Yoko Kanno", "Joe Hisaishi", "Ryuichi Sakamoto", "Kenji Kawai"], "correct": 1},
    {"id": "t168", "question": "Combien de films Joe Hisaishi a-t-il composés pour Ghibli ?", "options": ["5", "8", "11", "15"], "correct": 2},
    {"id": "t169", "question": "Quel compositeur Disney a été comparé à Hisaishi ?", "options": ["Alan Menken", "Hans Zimmer", "Thomas Newman", "Michael Giacchino"], "correct": 3},
    {"id": "t170", "question": "Pour quel film Pixar Michael Giacchino a-t-il gagné l'Oscar ?", "options": ["The Incredibles", "Ratatouille", "Up", "Inside Out"], "correct": 2},
    {"id": "t171", "question": "Combien de films Pixar Michael Giacchino a-t-il composés ?", "options": ["3", "5", "7", "Plus de 7"], "correct": 3},
    {"id": "t172", "question": "Quel autre franchise Giacchino a-t-il composée ?", "options": ["Star Wars", "Star Trek", "Marvel", "Les trois"], "correct": 3},
    {"id": "t173", "question": "Quel film Star Wars Giacchino a-t-il composé ?", "options": ["Le Réveil de la Force", "Rogue One", "Les Derniers Jedi", "Solo"], "correct": 1},
    {"id": "t174", "question": "Pourquoi Giacchino a-t-il été choisi pour Rogue One ?", "options": ["Plan initial", "Alexandre Desplat indisponible", "Recommandation", "Test réussi"], "correct": 1},
    {"id": "t175", "question": "Combien de temps Giacchino a-t-il eu pour composer Rogue One ?", "options": ["2 semaines", "4 semaines", "8 semaines", "12 semaines"], "correct": 1},
    {"id": "t176", "question": "Qui était le compositeur original prévu pour Rogue One ?", "options": ["John Williams", "Alexandre Desplat", "Hans Zimmer", "Danny Elfman"], "correct": 1},
    {"id": "t177", "question": "Qui compose la musique de tous les films Star Wars principaux ?", "options": ["John Williams", "Michael Giacchino", "Ludwig Göransson", "Variable"], "correct": 0},
    {"id": "t178", "question": "Combien de films Star Wars John Williams a-t-il composés ?", "options": ["6", "9", "11", "Tous les épisodes"], "correct": 3},
    {"id": "t179", "question": "Quel âge avait John Williams quand il a composé Rise of Skywalker ?", "options": ["80 ans", "85 ans", "87 ans", "90 ans"], "correct": 2},
    {"id": "t180", "question": "Combien d'Oscars John Williams a-t-il remportés ?", "options": ["3", "5", "7", "9"], "correct": 1},
    {"id": "t181", "question": "Combien de nominations aux Oscars John Williams a-t-il ?", "options": ["39", "45", "52", "54"], "correct": 2},
    {"id": "t182", "question": "Qui détient le record de nominations aux Oscars ?", "options": ["John Williams", "Walt Disney", "Katharine Hepburn", "Meryl Streep"], "correct": 1},
    {"id": "t183", "question": "Combien de nominations aux Oscars Walt Disney a-t-il eues ?", "options": ["48", "52", "59", "64"], "correct": 2},
    {"id": "t184", "question": "Combien d'Oscars Walt Disney a-t-il gagnés ?", "options": ["15", "22", "26", "32"], "correct": 1},
    {"id": "t185", "question": "Qui détient le record du plus d'Oscars gagnés ?", "options": ["Katharine Hepburn", "Walt Disney", "Edith Head", "John Ford"], "correct": 1},
    {"id": "t186", "question": "Quel Oscar spécial Walt Disney a-t-il reçu pour Blanche-Neige ?", "options": ["Oscar d'honneur", "Oscar avec 7 petits Oscars", "Oscar du mérite technique", "Oscar de la meilleure innovation"], "correct": 1},
    {"id": "t187", "question": "Qui a remis l'Oscar spécial de Blanche-Neige à Walt ?", "options": ["Charlie Chaplin", "Shirley Temple", "Clark Gable", "Bette Davis"], "correct": 1},
    {"id": "t188", "question": "Quel âge avait Shirley Temple lors de cette cérémonie ?", "options": ["8 ans", "10 ans", "12 ans", "14 ans"], "correct": 1},
    {"id": "t189", "question": "Combien de petites statuettes accompagnaient l'Oscar de Blanche-Neige ?", "options": ["5", "6", "7", "8"], "correct": 2},
    {"id": "t190", "question": "Pourquoi 7 petites statuettes ont-elles été données ?", "options": ["Représentant les 7 nains", "7 départements du film", "7 ans de production", "Tradition"], "correct": 0},
    {"id": "t191", "question": "Quel autre Oscar Disney a-t-il reçu pour une innovation technique ?", "options": ["Multiplane camera", "Fantasia sound", "Technicolor", "Tous ces éléments"], "correct": 3},
    {"id": "t192", "question": "Qu'est-ce que la caméra multiplane ?", "options": ["Une caméra 3D", "Un système de plans superposés pour la profondeur", "Une caméra rotative", "Une invention Pixar"], "correct": 1},
    {"id": "t193", "question": "Dans quel court-métrage la caméra multiplane a-t-elle été utilisée pour la première fois ?", "options": ["Steamboat Willie", "The Old Mill", "Flowers and Trees", "Three Little Pigs"], "correct": 1},
    {"id": "t194", "question": "Quel Oscar The Old Mill a-t-il remporté ?", "options": ["Meilleur court-métrage animé", "Oscar technique", "Les deux", "Aucun"], "correct": 2},
    {"id": "t195", "question": "Combien de plans la caméra multiplane pouvait-elle gérer ?", "options": ["3", "5", "7", "9"], "correct": 2},
    {"id": "t196", "question": "Combien coûtait la caméra multiplane originale ?", "options": ["10 000 $", "30 000 $", "70 000 $", "100 000 $"], "correct": 2},
    {"id": "t197", "question": "Où peut-on voir la caméra multiplane aujourd'hui ?", "options": ["Smithsonian", "Walt Disney Family Museum", "Disney Parks", "Elle a été détruite"], "correct": 1},
    {"id": "t198", "question": "Où se trouve le Walt Disney Family Museum ?", "options": ["Los Angeles", "Orlando", "San Francisco", "Marceline"], "correct": 2},
    {"id": "t199", "question": "Qui a fondé le Walt Disney Family Museum ?", "options": ["The Walt Disney Company", "La famille Disney", "L'État de Californie", "Des fans"], "correct": 1},
    {"id": "t200", "question": "En quelle année le Walt Disney Family Museum a-t-il ouvert ?", "options": ["2005", "2009", "2012", "2015"], "correct": 1}
];

// Export pour utilisation
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { taramquestions };
}
