// Questions Disney - Niveau Bambi (Facile) - 200 questions
const bambiquestions = [
    {"id": "b1", "question": "Quel est le nom du faon dans le film Bambi ?", "options": ["Panpan", "Bambi", "Fleur", "Ronno"], "correct": 1},
    {"id": "b2", "question": "Qui est le meilleur ami lapin de Bambi ?", "options": ["Fleur", "Panpan", "Ronno", "Faline"], "correct": 1},
    {"id": "b3", "question": "Comment s'appelle la mouffette dans Bambi ?", "options": ["Panpan", "Fleur", "Bambi", "Ronno"], "correct": 1},
    {"id": "b4", "question": "Quel animal est Simba ?", "options": ["Tigre", "Lion", "Guépard", "Panthère"], "correct": 1},
    {"id": "b5", "question": "Dans quel film Disney trouve-t-on le génie bleu ?", "options": ["La Petite Sirène", "Aladdin", "Hercule", "Mulan"], "correct": 1},
    {"id": "b6", "question": "Quelle princesse a des cheveux très longs ?", "options": ["Cendrillon", "Belle", "Raiponce", "Aurore"], "correct": 2},
    {"id": "b7", "question": "Quel est le nom du poisson ami de Némo ?", "options": ["Gill", "Dory", "Bruce", "Crush"], "correct": 1},
    {"id": "b8", "question": "De quelle couleur est Stitch ?", "options": ["Rouge", "Vert", "Bleu", "Jaune"], "correct": 2},
    {"id": "b9", "question": "Qui chante 'Libérée, Délivrée' ?", "options": ["Anna", "Elsa", "Olaf", "Kristoff"], "correct": 1},
    {"id": "b10", "question": "Quel animal est Dumbo ?", "options": ["Girafe", "Éléphant", "Hippopotame", "Rhinocéros"], "correct": 1},
    {"id": "b11", "question": "Dans 'Le Roi Lion', qui est le méchant oncle ?", "options": ["Mufasa", "Scar", "Timon", "Pumbaa"], "correct": 1},
    {"id": "b12", "question": "Quelle princesse vit sous la mer ?", "options": ["Jasmine", "Pocahontas", "Ariel", "Mulan"], "correct": 2},
    {"id": "b13", "question": "De quelle couleur est la robe de Cendrillon ?", "options": ["Rose", "Bleue", "Verte", "Jaune"], "correct": 1},
    {"id": "b14", "question": "Qui est le père de Simba ?", "options": ["Scar", "Mufasa", "Rafiki", "Zazu"], "correct": 1},
    {"id": "b15", "question": "Combien de nains y a-t-il dans Blanche-Neige ?", "options": ["5", "6", "7", "8"], "correct": 2},
    {"id": "b16", "question": "Quel animal est Baloo ?", "options": ["Ours", "Gorille", "Orang-outan", "Singe"], "correct": 0},
    {"id": "b17", "question": "Dans quel pays se déroule Mulan ?", "options": ["Japon", "Corée", "Chine", "Vietnam"], "correct": 2},
    {"id": "b18", "question": "Quel est le prénom de la fée dans Peter Pan ?", "options": ["Clochette", "Fée Bleue", "Marraine", "Flora"], "correct": 0},
    {"id": "b19", "question": "Qui est le méchant dans La Petite Sirène ?", "options": ["Maléfique", "Ursula", "Cruella", "La Reine"], "correct": 1},
    {"id": "b20", "question": "Quel objet Cendrillon perd-elle au bal ?", "options": ["Sa bague", "Son collier", "Sa pantoufle", "Son gant"], "correct": 2},
    {"id": "b21", "question": "Comment s'appelle le bonhomme de neige dans La Reine des Neiges ?", "options": ["Sven", "Kristoff", "Olaf", "Hans"], "correct": 2},
    {"id": "b22", "question": "Quel animal est Pumbaa ?", "options": ["Suricate", "Phacochère", "Sanglier", "Hyène"], "correct": 1},
    {"id": "b23", "question": "Quel est le nom du chien dans 'La Belle et le Clochard' ?", "options": ["Clochard", "Max", "Pluto", "Dingo"], "correct": 0},
    {"id": "b24", "question": "Quel personnage dit 'Ohana signifie famille' ?", "options": ["Nani", "Stitch", "Lilo", "Jumba"], "correct": 2},
    {"id": "b25", "question": "Quel est le nom du château de Disneyland Paris ?", "options": ["Château de la Belle au Bois Dormant", "Château de Cendrillon", "Château d'Arendelle", "Château de la Bête"], "correct": 0},
    {"id": "b26", "question": "Quel est le nom du rat cuisinier dans Ratatouille ?", "options": ["Emile", "Rémy", "Django", "Gusteau"], "correct": 1},
    {"id": "b27", "question": "Quelle princesse embrasse une grenouille ?", "options": ["Belle", "Tiana", "Jasmine", "Cendrillon"], "correct": 1},
    {"id": "b28", "question": "Comment s'appelle le père de Némo ?", "options": ["Martin", "Marin", "Marcel", "Maurice"], "correct": 1},
    {"id": "b29", "question": "Quel est le nom du cowboy dans Toy Story ?", "options": ["Buzz", "Woody", "Rex", "Jessie"], "correct": 1},
    {"id": "b30", "question": "Qui est la méchante reine dans Blanche-Neige ?", "options": ["Maléfique", "Grimhilde", "Ursula", "Lady Tremaine"], "correct": 1},
    {"id": "b31", "question": "Quel animal est Timon ?", "options": ["Phacochère", "Suricate", "Hyène", "Lion"], "correct": 1},
    {"id": "b32", "question": "Dans quel film trouve-t-on le tapis volant ?", "options": ["Peter Pan", "Aladdin", "Le Roi Lion", "Cendrillon"], "correct": 1},
    {"id": "b33", "question": "Quelle est la couleur des cheveux d'Ariel ?", "options": ["Blonde", "Brune", "Rousse", "Noire"], "correct": 2},
    {"id": "b34", "question": "Quel est le nom du dragon dans Mulan ?", "options": ["Mushu", "Khan", "Cri-Kee", "Shan Yu"], "correct": 0},
    {"id": "b35", "question": "Qui est le méchant dans Le Roi Lion ?", "options": ["Mufasa", "Zazu", "Scar", "Rafiki"], "correct": 2},
    {"id": "b36", "question": "Quel objet magique possède la Bête ?", "options": ["Un miroir", "Une rose", "Un livre", "Une horloge"], "correct": 1},
    {"id": "b37", "question": "Comment s'appelle le prince dans La Petite Sirène ?", "options": ["Adam", "Philippe", "Eric", "Ferdinand"], "correct": 2},
    {"id": "b38", "question": "Quel est le nom de l'oiseau dans Aladdin ?", "options": ["Iago", "Zazu", "Flit", "Archimède"], "correct": 0},
    {"id": "b39", "question": "Quelle princesse dort pendant 100 ans ?", "options": ["Cendrillon", "Blanche-Neige", "Aurore", "Belle"], "correct": 2},
    {"id": "b40", "question": "Quel est le nom du cheval de Raiponce ?", "options": ["Philippe", "Maximus", "Khan", "Samson"], "correct": 1},
    {"id": "b41", "question": "Qui est le sidekick de Maui dans Vaiana ?", "options": ["Pua", "Heihei", "Tamatoa", "Te Fiti"], "correct": 1},
    {"id": "b42", "question": "Quel fruit empoisonne Blanche-Neige ?", "options": ["Poire", "Orange", "Pomme", "Banane"], "correct": 2},
    {"id": "b43", "question": "Comment s'appelle le petit frère d'Anna ?", "options": ["Kristoff", "Hans", "Elle n'a pas de frère", "Olaf"], "correct": 2},
    {"id": "b44", "question": "Quel est le nom de la soeur d'Elsa ?", "options": ["Belle", "Raiponce", "Anna", "Ariel"], "correct": 2},
    {"id": "b45", "question": "Qui est le créateur de Pinocchio ?", "options": ["Geppetto", "Jiminy", "Figaro", "Stromboli"], "correct": 0},
    {"id": "b46", "question": "Quel insecte est Jiminy Cricket ?", "options": ["Sauterelle", "Grillon", "Fourmi", "Coccinelle"], "correct": 1},
    {"id": "b47", "question": "De quelle couleur est le nez de Pinocchio quand il ment ?", "options": ["Rouge", "Il s'allonge", "Bleu", "Vert"], "correct": 1},
    {"id": "b48", "question": "Quel est le nom du chat dans Pinocchio ?", "options": ["Figaro", "Lucifer", "Marie", "Thomas"], "correct": 0},
    {"id": "b49", "question": "Comment s'appelle la baleine dans Pinocchio ?", "options": ["Monstro", "Moby", "Willy", "Jonas"], "correct": 0},
    {"id": "b50", "question": "Quel personnage transforme Cendrillon pour le bal ?", "options": ["Fée Clochette", "Fée Bleue", "Marraine la Bonne Fée", "Flora"], "correct": 2},
    {"id": "b51", "question": "Quel est le nom du chat méchant dans Cendrillon ?", "options": ["Figaro", "Lucifer", "Thomas", "Scat Cat"], "correct": 1},
    {"id": "b52", "question": "Comment s'appellent les souris dans Cendrillon ?", "options": ["Jack et Gus", "Tom et Jerry", "Mickey et Minnie", "Bernard et Bianca"], "correct": 0},
    {"id": "b53", "question": "Quelle heure sonne quand Cendrillon doit partir ?", "options": ["11 heures", "Minuit", "10 heures", "1 heure"], "correct": 1},
    {"id": "b54", "question": "Combien de belles-soeurs a Cendrillon ?", "options": ["1", "2", "3", "4"], "correct": 1},
    {"id": "b55", "question": "Quel est le nom du prince dans Cendrillon ?", "options": ["Philippe", "Adam", "Charmant", "Eric"], "correct": 2},
    {"id": "b56", "question": "Qui est le meilleur ami de Mickey Mouse ?", "options": ["Dingo", "Donald", "Pluto", "Pat"], "correct": 1},
    {"id": "b57", "question": "Quel est le nom de la petite amie de Mickey ?", "options": ["Daisy", "Minnie", "Clarabelle", "Lilly"], "correct": 1},
    {"id": "b58", "question": "Quel est le nom du chien de Mickey ?", "options": ["Dingo", "Max", "Pluto", "Pat"], "correct": 2},
    {"id": "b59", "question": "De quelle couleur sont les chaussures de Mickey ?", "options": ["Noires", "Jaunes", "Rouges", "Blanches"], "correct": 1},
    {"id": "b60", "question": "Qui est l'oncle de Donald Duck ?", "options": ["Picsou", "Géo Trouvetou", "Gontran", "Popop"], "correct": 0},
    {"id": "b61", "question": "Combien de neveux a Donald Duck ?", "options": ["2", "3", "4", "5"], "correct": 1},
    {"id": "b62", "question": "Comment s'appellent les neveux de Donald ?", "options": ["Riri, Fifi, Loulou", "Tom, Dick, Harry", "Huey, Dewey, Louie", "A et B"], "correct": 0},
    {"id": "b63", "question": "Quelle est la petite amie de Donald ?", "options": ["Minnie", "Daisy", "Clarabelle", "Lilly"], "correct": 1},
    {"id": "b64", "question": "Quel animal est Dingo ?", "options": ["Chien", "Chat", "Ours", "Loup"], "correct": 0},
    {"id": "b65", "question": "Comment s'appelle le fils de Dingo ?", "options": ["Junior", "Max", "Pete", "PJ"], "correct": 1},
    {"id": "b66", "question": "Qui est le méchant récurrent de Mickey ?", "options": ["Pat Hibulaire", "Cruella", "Maléfique", "Jafar"], "correct": 0},
    {"id": "b67", "question": "Quel personnage Disney a de grandes oreilles rondes ?", "options": ["Donald", "Dingo", "Mickey", "Pluto"], "correct": 2},
    {"id": "b68", "question": "Dans quel film apparaît Buzz l'Éclair ?", "options": ["Cars", "Toy Story", "Les Indestructibles", "Monstres et Cie"], "correct": 1},
    {"id": "b69", "question": "Quelle est la phrase célèbre de Buzz ?", "options": ["Vers l'infini et au-delà!", "Je suis ton père", "Hakuna Matata", "Ohana"], "correct": 0},
    {"id": "b70", "question": "Quel est le nom du dinosaure vert dans Toy Story ?", "options": ["Dino", "Rex", "Trixie", "Reptar"], "correct": 1},
    {"id": "b71", "question": "Comment s'appelle la bergère dans Toy Story ?", "options": ["Bo Peep", "Jessie", "Barbie", "Betty"], "correct": 0},
    {"id": "b72", "question": "Quel est le nom du cochon tirelire dans Toy Story ?", "options": ["Hamm", "Piggy", "Porky", "Wilbur"], "correct": 0},
    {"id": "b73", "question": "Qui est la cowgirl dans Toy Story 2 ?", "options": ["Bo Peep", "Barbie", "Jessie", "Betty"], "correct": 2},
    {"id": "b74", "question": "Quel est le nom du cheval de Woody ?", "options": ["Maximus", "Pile-Poil", "Khan", "Philippe"], "correct": 1},
    {"id": "b75", "question": "Comment s'appelle le méchant ours en peluche dans Toy Story 3 ?", "options": ["Teddy", "Lotso", "Cuddles", "Bear"], "correct": 1},
    {"id": "b76", "question": "Quel est le vrai nom d'Andy dans Toy Story ?", "options": ["Andrew Davis", "Andy Phillips", "Andy Davis", "Andrew Smith"], "correct": 2},
    {"id": "b77", "question": "Quel monstre est vert avec un oeil dans Monstres et Cie ?", "options": ["Sulli", "Bob", "Randall", "Léon"], "correct": 1},
    {"id": "b78", "question": "Quel monstre est bleu et poilu dans Monstres et Cie ?", "options": ["Bob", "Sulli", "Randall", "George"], "correct": 1},
    {"id": "b79", "question": "Comment s'appelle la petite fille dans Monstres et Cie ?", "options": ["Mary", "Boo", "Sally", "Emma"], "correct": 1},
    {"id": "b80", "question": "Que produisent les monstres comme énergie ?", "options": ["Électricité", "Cris d'enfants", "Lumière", "Chaleur"], "correct": 1},
    {"id": "b81", "question": "Quel est le nom du méchant caméléon dans Monstres et Cie ?", "options": ["Leon", "Randall", "Pascal", "Rango"], "correct": 1},
    {"id": "b82", "question": "De quelle couleur est Flash McQueen dans Cars ?", "options": ["Bleu", "Rouge", "Vert", "Jaune"], "correct": 1},
    {"id": "b83", "question": "Quel est le numéro de Flash McQueen ?", "options": ["85", "95", "105", "115"], "correct": 1},
    {"id": "b84", "question": "Comment s'appelle la voiture de dépannage dans Cars ?", "options": ["Mater", "Sally", "Doc", "Luigi"], "correct": 0},
    {"id": "b85", "question": "Dans quelle ville se passe l'histoire de Cars ?", "options": ["Springfield", "Radiator Springs", "Motor City", "Piston Peak"], "correct": 1},
    {"id": "b86", "question": "Qui est le Doc Hudson dans Cars ?", "options": ["Un ancien médecin", "Un ancien champion de course", "Un mécanicien", "Un juge"], "correct": 1},
    {"id": "b87", "question": "Quel est le nom de la Porsche bleue dans Cars ?", "options": ["Sally", "Flo", "Ramone", "Lizzie"], "correct": 0},
    {"id": "b88", "question": "Quel personnage Disney est une voiture de course italienne ?", "options": ["Luigi", "Guido", "Francesco", "Max"], "correct": 2},
    {"id": "b89", "question": "Quel est le nom du poisson-clown père de Némo ?", "options": ["Martin", "Marin", "Marcel", "Maurice"], "correct": 1},
    {"id": "b90", "question": "Quelle est la particularité de Dory ?", "options": ["Elle est aveugle", "Elle perd la mémoire", "Elle est sourde", "Elle ne sait pas nager"], "correct": 1},
    {"id": "b91", "question": "Où vit Némo au début du film ?", "options": ["Dans une épave", "Dans une anémone", "Dans un récif", "Dans une grotte"], "correct": 1},
    {"id": "b92", "question": "Qui capture Némo ?", "options": ["Un requin", "Un plongeur", "Un pêcheur", "Une pieuvre"], "correct": 1},
    {"id": "b93", "question": "Où Némo se retrouve-t-il après sa capture ?", "options": ["Dans un restaurant", "Dans un aquarium", "Dans un zoo", "Dans un laboratoire"], "correct": 1},
    {"id": "b94", "question": "Comment s'appelle le requin végétarien dans Némo ?", "options": ["Anchor", "Chum", "Bruce", "Jaws"], "correct": 2},
    {"id": "b95", "question": "Quelle est la devise des requins dans Némo ?", "options": ["Les poissons sont nos amis", "Pas de pitié", "Manger ou être mangé", "La mer nous appartient"], "correct": 0},
    {"id": "b96", "question": "Quel est le nom de la tortue dans Némo ?", "options": ["Squirt", "Crush", "Shell", "Turbo"], "correct": 1},
    {"id": "b97", "question": "Comment s'appelle le jeune tortue fils de Crush ?", "options": ["Squirt", "Shell", "Turbo", "Junior"], "correct": 0},
    {"id": "b98", "question": "Dans quel océan se déroule l'histoire de Némo ?", "options": ["Atlantique", "Pacifique", "Indien", "Arctique"], "correct": 1},
    {"id": "b99", "question": "Quelle princesse Disney est chinoise ?", "options": ["Jasmine", "Pocahontas", "Mulan", "Moana"], "correct": 2},
    {"id": "b100", "question": "Quelle princesse Disney est amérindienne ?", "options": ["Moana", "Mulan", "Pocahontas", "Jasmine"], "correct": 2},
    {"id": "b101", "question": "Quelle princesse Disney est hawaïenne/polynésienne ?", "options": ["Lilo", "Moana", "Pocahontas", "Mulan"], "correct": 1},
    {"id": "b102", "question": "Quelle princesse Disney vit à Agrabah ?", "options": ["Mulan", "Pocahontas", "Jasmine", "Tiana"], "correct": 2},
    {"id": "b103", "question": "Quelle princesse Disney est française ?", "options": ["Cendrillon", "Belle", "Aurore", "Toutes ces réponses"], "correct": 3},
    {"id": "b104", "question": "Quelle princesse Disney est écossaise ?", "options": ["Merida", "Anna", "Elsa", "Aurora"], "correct": 0},
    {"id": "b105", "question": "Quelle princesse Disney a un tigre comme animal de compagnie ?", "options": ["Mulan", "Pocahontas", "Jasmine", "Moana"], "correct": 2},
    {"id": "b106", "question": "Quelle princesse Disney a un raton laveur comme ami ?", "options": ["Cendrillon", "Pocahontas", "Raiponce", "Blanche-Neige"], "correct": 1},
    {"id": "b107", "question": "Quelle princesse Disney a un caméléon comme compagnon ?", "options": ["Raiponce", "Tiana", "Moana", "Merida"], "correct": 0},
    {"id": "b108", "question": "Comment s'appelle le caméléon de Raiponce ?", "options": ["Leon", "Pascal", "Rango", "Camo"], "correct": 1},
    {"id": "b109", "question": "Quel est le pouvoir magique de Raiponce ?", "options": ["Voler", "Ses cheveux guérissent", "Parler aux animaux", "Contrôler l'eau"], "correct": 1},
    {"id": "b110", "question": "Qui enlève Raiponce bébé ?", "options": ["Une sorcière", "Mère Gothel", "Une fée", "Un dragon"], "correct": 1},
    {"id": "b111", "question": "Quel est le vrai nom de Flynn Rider ?", "options": ["Eugène Fitzherbert", "Eric Fitzpatrick", "Edward Flynn", "Edmund Rider"], "correct": 0},
    {"id": "b112", "question": "Quel objet Raiponce utilise-t-elle comme arme ?", "options": ["Une épée", "Une poêle à frire", "Un balai", "Un bâton"], "correct": 1},
    {"id": "b113", "question": "Quelle couleur deviennent les cheveux de Raiponce à la fin ?", "options": ["Blonds", "Bruns", "Roux", "Blancs"], "correct": 1},
    {"id": "b114", "question": "Quel est le nom de l'île de Vaiana ?", "options": ["Hawaii", "Motunui", "Tahiti", "Bora Bora"], "correct": 1},
    {"id": "b115", "question": "Que doit rendre Vaiana à Te Fiti ?", "options": ["Son collier", "Son coeur", "Sa couronne", "Son trident"], "correct": 1},
    {"id": "b116", "question": "Quel animal accompagne Vaiana sur son bateau ?", "options": ["Un chien", "Un cochon", "Un poulet et un cochon", "Un perroquet"], "correct": 2},
    {"id": "b117", "question": "Comment s'appelle le cochon de Vaiana ?", "options": ["Pua", "Heihei", "Porky", "Wilbur"], "correct": 0},
    {"id": "b118", "question": "Comment s'appelle le coq stupide dans Vaiana ?", "options": ["Pua", "Heihei", "Clucky", "Rooster"], "correct": 1},
    {"id": "b119", "question": "Qui est Maui ?", "options": ["Un dieu", "Un demi-dieu", "Un héros", "Un roi"], "correct": 1},
    {"id": "b120", "question": "Quel objet magique possède Maui ?", "options": ["Un trident", "Un hameçon", "Une lance", "Un bouclier"], "correct": 1},
    {"id": "b121", "question": "En quoi peut se transformer Maui ?", "options": ["En animaux", "En plantes", "En eau", "En feu"], "correct": 0},
    {"id": "b122", "question": "Qui est le grand-mère de Vaiana ?", "options": ["Tala", "Sina", "Te Fiti", "Moana"], "correct": 0},
    {"id": "b123", "question": "Quel est le nom du crabe géant brillant dans Vaiana ?", "options": ["Sebastian", "Tamatoa", "Jacques", "Crabby"], "correct": 1},
    {"id": "b124", "question": "Quelle chanson chante Tamatoa ?", "options": ["Shiny", "How Far I'll Go", "You're Welcome", "We Know The Way"], "correct": 0},
    {"id": "b125", "question": "Quelle chanson Maui chante-t-il ?", "options": ["Shiny", "How Far I'll Go", "You're Welcome", "We Know The Way"], "correct": 2},
    {"id": "b126", "question": "Quel est le titre français de 'Frozen' ?", "options": ["Gelée", "La Reine des Neiges", "Frozen", "Le Royaume de Glace"], "correct": 1},
    {"id": "b127", "question": "Quel est le pouvoir d'Elsa ?", "options": ["Le feu", "La glace", "Le vent", "L'eau"], "correct": 1},
    {"id": "b128", "question": "Comment s'appelle le renne de Kristoff ?", "options": ["Sven", "Olaf", "Hans", "Erik"], "correct": 0},
    {"id": "b129", "question": "Quel prince trahit Anna dans La Reine des Neiges ?", "options": ["Kristoff", "Hans", "Eric", "Adam"], "correct": 1},
    {"id": "b130", "question": "De quel royaume viennent Anna et Elsa ?", "options": ["Corona", "Arendelle", "Dunbroch", "Atlantica"], "correct": 1},
    {"id": "b131", "question": "Quel est le métier de Kristoff ?", "options": ["Prince", "Marchand de glace", "Bûcheron", "Pêcheur"], "correct": 1},
    {"id": "b132", "question": "Qu'est-ce qu'Olaf aime le plus ?", "options": ["La neige", "Les câlins chauds", "L'hiver", "Le froid"], "correct": 1},
    {"id": "b133", "question": "Quelle chanson Anna chante-t-elle à sa porte ?", "options": ["Let It Go", "Do You Want to Build a Snowman", "For the First Time in Forever", "Love is an Open Door"], "correct": 1},
    {"id": "b134", "question": "Quelle est la chanson la plus célèbre de La Reine des Neiges ?", "options": ["Let It Go", "Do You Want to Build a Snowman", "For the First Time in Forever", "Into the Unknown"], "correct": 0},
    {"id": "b135", "question": "Quel animal est Sven ?", "options": ["Un cheval", "Un renne", "Un élan", "Un cerf"], "correct": 1},
    {"id": "b136", "question": "Quel est le nom du royaume sous-marin d'Ariel ?", "options": ["Océania", "Atlantica", "Aquatica", "Marineland"], "correct": 1},
    {"id": "b137", "question": "Comment s'appelle le père d'Ariel ?", "options": ["Poséidon", "Triton", "Neptune", "Aquaman"], "correct": 1},
    {"id": "b138", "question": "Combien de soeurs a Ariel ?", "options": ["4", "5", "6", "7"], "correct": 2},
    {"id": "b139", "question": "Quel est le nom du crabe dans La Petite Sirène ?", "options": ["Jacques", "Sebastian", "Homard", "Crabby"], "correct": 1},
    {"id": "b140", "question": "Comment s'appelle le poisson ami d'Ariel ?", "options": ["Nemo", "Polochon", "Dory", "Gill"], "correct": 1},
    {"id": "b141", "question": "Que veut Ariel plus que tout ?", "options": ["Des bijoux", "Devenir humaine", "Être reine", "Voyager"], "correct": 1},
    {"id": "b142", "question": "Qu'échange Ariel contre ses jambes ?", "options": ["Ses cheveux", "Sa voix", "Sa beauté", "Son coeur"], "correct": 1},
    {"id": "b143", "question": "Quelle chanson Ariel chante-t-elle dans sa grotte ?", "options": ["Part of Your World", "Under the Sea", "Kiss the Girl", "Poor Unfortunate Souls"], "correct": 0},
    {"id": "b144", "question": "Quelle chanson Sebastian chante-t-il ?", "options": ["Part of Your World", "Under the Sea", "Kiss the Girl", "Les Poissons"], "correct": 1},
    {"id": "b145", "question": "Comment s'appelle le chien du prince Eric ?", "options": ["Max", "Pluto", "Buddy", "Rex"], "correct": 0},
    {"id": "b146", "question": "De quelle couleur est la fleur que Belle préfère ?", "options": ["Rouge", "Rose", "Blanche", "Jaune"], "correct": 0},
    {"id": "b147", "question": "Comment s'appelle le cheval de Belle ?", "options": ["Maximus", "Philippe", "Khan", "Samson"], "correct": 1},
    {"id": "b148", "question": "Quel est le métier du père de Belle ?", "options": ["Forgeron", "Inventeur", "Fermier", "Libraire"], "correct": 1},
    {"id": "b149", "question": "Comment s'appelle le père de Belle ?", "options": ["Georges", "Maurice", "Henri", "Pierre"], "correct": 1},
    {"id": "b150", "question": "Qui est amoureux de Belle au village ?", "options": ["Le prince", "Gaston", "Lefou", "Le libraire"], "correct": 1},
    {"id": "b151", "question": "Comment s'appelle le sidekick de Gaston ?", "options": ["Lefou", "Lepetit", "Legrand", "Lebeau"], "correct": 0},
    {"id": "b152", "question": "Quel objet enchante la Bête avec le temps ?", "options": ["Un miroir", "Une rose", "Une horloge", "Un chandelier"], "correct": 1},
    {"id": "b153", "question": "Comment s'appelle le chandelier dans La Belle et la Bête ?", "options": ["Lumière", "Big Ben", "Zip", "Chip"], "correct": 0},
    {"id": "b154", "question": "Comment s'appelle l'horloge dans La Belle et la Bête ?", "options": ["Lumière", "Big Ben", "Tic-Tac", "Clock"], "correct": 1},
    {"id": "b155", "question": "Comment s'appelle la théière dans La Belle et la Bête ?", "options": ["Mrs Potts", "Mrs Tea", "Mme Samovar", "Mrs Kettle"], "correct": 2},
    {"id": "b156", "question": "Comment s'appelle la petite tasse fils de Mrs Potts ?", "options": ["Cup", "Chip", "Zip", "Tip"], "correct": 1},
    {"id": "b157", "question": "Quelle est la chanson la plus connue de La Belle et la Bête ?", "options": ["Be Our Guest", "Beauty and the Beast", "Gaston", "Belle"], "correct": 1},
    {"id": "b158", "question": "Quelle chanson les objets enchantés chantent-ils ?", "options": ["Be Our Guest", "Beauty and the Beast", "Gaston", "Belle"], "correct": 0},
    {"id": "b159", "question": "Quelle est l'activité préférée de Belle ?", "options": ["Danser", "Chanter", "Lire", "Cuisiner"], "correct": 2},
    {"id": "b160", "question": "De quelle couleur est la robe de bal de Belle ?", "options": ["Bleue", "Rose", "Jaune", "Blanche"], "correct": 2},
    {"id": "b161", "question": "Quel personnage Disney vole grâce à de la poussière de fée ?", "options": ["Dumbo", "Peter Pan", "Aladdin", "Mary Poppins"], "correct": 1},
    {"id": "b162", "question": "Où vit Peter Pan ?", "options": ["Neverland", "Wonderland", "Narnia", "Oz"], "correct": 0},
    {"id": "b163", "question": "Qui est le méchant dans Peter Pan ?", "options": ["Capitaine Barbe Noire", "Capitaine Crochet", "Capitaine Sparrow", "Capitaine Nemo"], "correct": 1},
    {"id": "b164", "question": "Quelle main le Capitaine Crochet a-t-il perdue ?", "options": ["La droite", "La gauche", "Les deux", "Aucune"], "correct": 1},
    {"id": "b165", "question": "Quel animal a mangé la main du Capitaine Crochet ?", "options": ["Un requin", "Un crocodile", "Une baleine", "Un serpent"], "correct": 1},
    {"id": "b166", "question": "Qu'a avalé le crocodile dans Peter Pan ?", "options": ["Une montre", "Un réveil", "Une cloche", "Un sifflet"], "correct": 1},
    {"id": "b167", "question": "Comment s'appellent les enfants que Peter Pan emmène ?", "options": ["Wendy, John et Michael", "Alice, Bob et Charlie", "Mary, Peter et Paul", "Anna, Elsa et Olaf"], "correct": 0},
    {"id": "b168", "question": "Comment s'appelle la fée de Peter Pan ?", "options": ["Fée Bleue", "Clochette", "Marraine", "Flora"], "correct": 1},
    {"id": "b169", "question": "De quoi a peur le Capitaine Crochet ?", "options": ["De l'eau", "Du crocodile", "De Peter Pan", "Du noir"], "correct": 1},
    {"id": "b170", "question": "Que faut-il pour voler avec Peter Pan ?", "options": ["Des ailes", "De la poussière de fée et des pensées heureuses", "Un tapis magique", "Un balai"], "correct": 1},
    {"id": "b171", "question": "Qui vit dans le terrier dans Alice au Pays des Merveilles ?", "options": ["Le Chapelier", "Le Lapin Blanc", "La Chenille", "Le Chat"], "correct": 1},
    {"id": "b172", "question": "Que regarde toujours le Lapin Blanc ?", "options": ["Sa montre", "Le ciel", "Le sol", "Un miroir"], "correct": 0},
    {"id": "b173", "question": "Qui organise la Tea Party dans Alice ?", "options": ["La Reine", "Le Lapin", "Le Chapelier Fou", "Alice"], "correct": 2},
    {"id": "b174", "question": "De quelle couleur est le Chat du Cheshire ?", "options": ["Bleu", "Rose et violet", "Orange", "Vert"], "correct": 1},
    {"id": "b175", "question": "Quelle reine veut couper des têtes ?", "options": ["La Reine des Neiges", "La Reine de Coeur", "La méchante Reine", "La Reine Blanche"], "correct": 1},
    {"id": "b176", "question": "Que fume la Chenille dans Alice ?", "options": ["Une pipe", "Un narguilé", "Une cigarette", "Rien"], "correct": 1},
    {"id": "b177", "question": "Quelle question pose sans cesse la Chenille ?", "options": ["Pourquoi?", "Comment?", "Qui es-tu?", "Où vas-tu?"], "correct": 2},
    {"id": "b178", "question": "Qu'arrive-t-il à Alice quand elle boit la potion ?", "options": ["Elle dort", "Elle rétrécit", "Elle vole", "Elle devient invisible"], "correct": 1},
    {"id": "b179", "question": "Qu'arrive-t-il à Alice quand elle mange le gâteau ?", "options": ["Elle dort", "Elle grandit", "Elle vole", "Elle devient invisible"], "correct": 1},
    {"id": "b180", "question": "Comment Alice est-elle arrivée au Pays des Merveilles ?", "options": ["Par une porte", "Par un terrier de lapin", "Par un miroir", "Par un rêve"], "correct": 1},
    {"id": "b181", "question": "Quel est le nom de l'héroïne de Rebelle ?", "options": ["Anna", "Elsa", "Merida", "Moana"], "correct": 2},
    {"id": "b182", "question": "Quelle arme Merida utilise-t-elle ?", "options": ["Une épée", "Un arc", "Une lance", "Une hache"], "correct": 1},
    {"id": "b183", "question": "En quoi la mère de Merida est-elle transformée ?", "options": ["En pierre", "En ours", "En arbre", "En cerf"], "correct": 1},
    {"id": "b184", "question": "De quelle couleur sont les cheveux de Merida ?", "options": ["Bruns", "Blonds", "Noirs", "Roux"], "correct": 3},
    {"id": "b185", "question": "Combien de petits frères a Merida ?", "options": ["1", "2", "3", "4"], "correct": 2},
    {"id": "b186", "question": "En quoi les frères de Merida sont-ils transformés ?", "options": ["En loups", "En oursons", "En renards", "En lapins"], "correct": 1},
    {"id": "b187", "question": "Qui transforme la famille de Merida ?", "options": ["Une fée", "Une sorcière", "Un magicien", "Un druide"], "correct": 1},
    {"id": "b188", "question": "Quel est le nom du cheval de Merida ?", "options": ["Maximus", "Angus", "Khan", "Philippe"], "correct": 1},
    {"id": "b189", "question": "Quel est le pouvoir du personnage principal de Coco ?", "options": ["Il voit les morts", "Il joue de la musique", "Il voyage dans le temps", "Il parle aux animaux"], "correct": 0},
    {"id": "b190", "question": "Comment s'appelle le garçon dans Coco ?", "options": ["Pedro", "Miguel", "Carlos", "Diego"], "correct": 1},
    {"id": "b191", "question": "Quel instrument Miguel veut-il jouer ?", "options": ["Piano", "Violon", "Guitare", "Trompette"], "correct": 2},
    {"id": "b192", "question": "Quel jour se déroule principalement Coco ?", "options": ["Noël", "Halloween", "Le Jour des Morts", "Pâques"], "correct": 2},
    {"id": "b193", "question": "Comment s'appelle le chien de Miguel ?", "options": ["Dante", "Max", "Buddy", "Rex"], "correct": 0},
    {"id": "b194", "question": "Quel type d'animal est Dante ?", "options": ["Un labrador", "Un chihuahua", "Un xoloitzcuintle", "Un berger"], "correct": 2},
    {"id": "b195", "question": "Qui est le vrai méchant dans Coco ?", "options": ["Héctor", "Ernesto de la Cruz", "La grand-mère", "Dante"], "correct": 1},
    {"id": "b196", "question": "Qui est Héctor dans Coco ?", "options": ["Un musicien mort", "L'arrière-grand-père de Miguel", "Les deux", "Un fantôme"], "correct": 2},
    {"id": "b197", "question": "Quelle chanson est célèbre dans Coco ?", "options": ["Un Poco Loco", "Remember Me", "The World Es Mi Familia", "Toutes ces réponses"], "correct": 3},
    {"id": "b198", "question": "Quel est le titre français de 'Up' ?", "options": ["Haut", "Là-Haut", "En Haut", "Vers le Haut"], "correct": 1},
    {"id": "b199", "question": "Comment s'appelle le vieil homme dans Là-Haut ?", "options": ["Karl", "Carl", "Charles", "Carlos"], "correct": 1},
    {"id": "b200", "question": "Comment Carl fait-il voler sa maison ?", "options": ["Avec des hélices", "Avec des ballons", "Avec de la magie", "Avec un moteur"], "correct": 1}
];

// Export pour utilisation
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { bambiquestions };
}
